### ISSUE TITLE
Could I have a sample data for demo

### ISSUE THREAD

**Issue by yy491** [han14466/gplearn_stock_dataframe#1]
Hi Han,

Appreciate for sharing the code and giving me the chance to learn.
It will be great if I could also get a data sample used in the demo.

Best wishes

Jeff

**Comment by han14466** [comment]
你可以看一下factor_mining_demo.py，数据是dataframe格式的，索引是时间和股票代码，columnname就是指标

**Comment by han14466** [comment]
> 
你可以看一下factor_mining_demo.py，数据是dataframe格式的，索引是时间和股票代码，columnname就是指标

**Comment by han14466** [comment]
> Hi Han,
> 
> Appreciate for sharing the code and giving me the chance to learn. It will be great if I could also get a data sample used in the demo.
> 
> Best wishes
> 
> Jeff

你可以看一下factor_mining_demo.py，数据是dataframe格式的，索引是时间和股票代码，columnname就是指标

**Comment by han14466** [comment]
也可以看一下functions_x.py中构建时序参数校验时的生成方式
